disabled_rules:
  - identifier_name
  - trailing_newline
  - trailing_whitespace
  - force_cast
  - force_try

line_length:
  warning: 250
  error: 1000

function_body_length:
  warning: 300
  error: 500