name: WIPFoundation
deploymentTarget:
  iOS: 14.0
  tvOS: 14.0
  macOS: 10.15
  watchOS: 7.0
fileGroups:
  - README.md
  - LICENSE.md
  - LinuxMain.swift
include:
  - project_targets.yml
  - project_schemes.yml