default_platform(:ios)

# Private lanes

lane :run_iOS_tests do
  scan(
    project: "WIPFoundation.xcodeproj",
    scheme: "WIPFoundation iOS"
  ) 
end

lane :run_tvOS_tests do
  scan(
    project: "WIPFoundation.xcodeproj", 
    scheme: "WIPFoundation tvOS"
  ) 
end

lane :run_macOS_tests do
  scan(
    project: "WIPFoundation.xcodeproj", 
    scheme: "WIPFoundation macOS"
  ) 
end

# Public lanes

desc "Run the tests"
lane :tests do
  run_macOS_tests
  run_iOS_tests
  run_tvOS_tests
end
