default_platform(:ios)

# Private lanes

lane :test do |options|
  scan(
    scheme: options[:scheme], 
    clean: true, 
    xcargs: "SWIFT_VERSION=#{options[:swift_version]}",
    destination: options[:destination]
  )
end

lane :build do |options|
  gym(
    project: "WIPFoundation.xcodeproj",
    configuration: "Debug",
    scheme: options[:scheme],
    xcargs: "SWIFT_VERSION=#{options[:swift_version]}",
    destination: options[:destination]
  )
end

# Public lanes

desc "Run tests"
lane :tests do
  test(destination: "platform=macOS", swift_version: "5.5", scheme: "WIPFoundation macOS")
  test(destination: "platform=iOS Simulator,OS=15.5,name=iPhone 13", swift_version: "5.5", scheme: "WIPFoundation iOS")
  test(destination: "platform=tvOS Simulator,OS=15.4,name=Apple TV", swift_version: "5.5", scheme: "WIPFoundation tvOS")
end

desc "Run tests on CI"
lane :tests_ci do
if ENV["DESTINATION"].include? "watchOS" then
  build(destination: ENV["DESTINATION"], swift_version: ENV["SWIFT_VERSION"], scheme: ENV["SCHEME"])
else
  test(destination: ENV["DESTINATION"], swift_version: ENV["SWIFT_VERSION"], scheme: ENV["SCHEME"])
end

end