name: CI

on: 
  push:
    branches:
      - master

jobs:

  iOS:
    name: Test iOS
    runs-on: macOS-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Test - iOS
        run: bundle exec fastlane run_iOS_tests
      # - name: iOS - ${{ matrix.destination }}
      #   run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "WIPFoundation.xcodeproj" -scheme "WIPFoundation iOS" -destination "${{ matrix.destination }}" clean test | xcpretty

  macOS_5_3:
    name: Test macOS (Swift 5.3)
    runs-on: macOS-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: macOS (Swift 5.3)
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "WIPFoundation.xcodeproj" -scheme "WIPFoundation macOS" -destination "platform=macOS" clean test | xcpretty
  
  # macOS_5_4:
  #   name: Test macOS (Swift 5.4)
  #   runs-on: macOS-10.15 
  #   env:
  #     DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: macOS (Swift 5.4)
  #       run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "WIPFoundation.xcodeproj" -scheme "WIPFoundation macOS" -destination "platform=macOS" clean test | xcpretty

  tvOS:
    name: Test tvOS 
    runs-on: macOS-10.15
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.3,name=Apple TV 4K"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "WIPFoundation.xcodeproj" -scheme "WIPFoundation tvOS" -destination "${{ matrix.destination }}" clean test | xcpretty

  watchOS:
    name: Build watchOS
    runs-on: macOS-10.15
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=7.2,name=Apple Watch Series 6 - 44mm"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: watchOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "WIPFoundation.xcodeproj" -scheme "WIPFoundation watchOS" -destination "${{ matrix.destination }}" clean build | xcpretty

  # Linux:
  #   name: Build Linux
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Swift
  #       uses: sersoft-gmbh/SwiftyActions@v1
  #       with:
  #         release-version: 5.4
  #     - name: Build Linux
  #       run: |
  #         swift build
  #         swift test