on: push
name: Test
jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and run xcodegen
        run: |
          brew install xcodegen
          xcodegen generate
#      - name: Run Fastlane tests
#        run: brew install fastlane



    
