on: push
name: After Push
jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: scripts/install_dependencies.sh
  run_tests:
    needs: install_dependencies
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: scripts/run_tests.sh



    
