name: Tests
on: push
env:
  DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer
jobs:
  install_dependencies:
    name: Install Dependencies / Run Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: scripts/install_dependencies.sh
      - name: Run tests
        run: scripts/run_tests.sh



    
